# Generated by Django 4.2.13 on 2024-05-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMesaServicio', '0002_tipoprocedimiento_solicitud_caso_solucioncaso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='casEstado',
            field=models.CharField(choices=[('Solicitada', 'Solicitada'), ('En proceso', 'En proceso'), ('Finalizada', 'Finalizada')], db_comment='', default='Solicitada', max_length=15),
        ),
    ]
