# Generated by Django 4.2.13 on 2024-05-29 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMesaServicio', '0003_alter_caso_casestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucioncaso',
            name='solTipoSolucion',
            field=models.CharField(choices=[('Parcial', 'Parcial'), ('Definitiva', 'Definitiva')], db_comment='Tipo de la solucuín, si es parcial o definitiva', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='caso',
            name='casCodigo',
            field=models.CharField(db_comment='Código único del caso', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='casEstado',
            field=models.CharField(choices=[('Solicitada', 'Solicitada'), ('En Proceso', 'En Proceso'), ('Finalizada', 'Finalizada')], default='Solicitada', max_length=15),
        ),
        migrations.AlterField(
            model_name='caso',
            name='casSolicitud',
            field=models.ForeignKey(db_comment='Hace referencia a la solicitud que generó el Caso', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.solicitud'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='casUsuario',
            field=models.ForeignKey(db_comment='Empleado de soporte técnico asignado al caso', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caso',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización'),
        ),
        migrations.AlterField(
            model_name='oficinaambiente',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización'),
        ),
        migrations.AlterField(
            model_name='oficinaambiente',
            name='ofiNombre',
            field=models.CharField(db_comment='Nombre de la oficina o ambiente', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='oficinaambiente',
            name='ofiTipo',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Formación', 'Formación')], db_comment='tipo de oficina', max_length=15),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solDescripcion',
            field=models.TextField(db_comment='Texto que describe las solicitud del empleado', max_length=1000),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solOficinaAmbiente',
            field=models.ForeignKey(db_comment='Hace referencia a la oficina o ambiente donde se encuentra el equipo de la solicitud', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.oficinaambiente'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solUsuario',
            field=models.ForeignKey(db_comment='Hace referencia al empleado que hace la solicitud', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solucioncaso',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización'),
        ),
        migrations.AlterField(
            model_name='solucioncaso',
            name='fechaHoraCreacion',
            field=models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro'),
        ),
        migrations.AlterField(
            model_name='solucioncaso',
            name='solCaso',
            field=models.ForeignKey(db_comment='Hace referencia al caso que genera la solución', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.caso'),
        ),
        migrations.AlterField(
            model_name='solucioncaso',
            name='solProcedimiento',
            field=models.TextField(db_comment='Texto del procedimiento realizado en la solución del caso', max_length=2000),
        ),
        migrations.AlterField(
            model_name='solucioncasotipoprocedimientos',
            name='solSolucionCaso',
            field=models.ForeignKey(db_comment='Hace referencia a la solución del Caso', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.solucioncaso'),
        ),
        migrations.AlterField(
            model_name='solucioncasotipoprocedimientos',
            name='solTipoProcedimiento',
            field=models.ForeignKey(db_comment='Hace referencia al tipo de procedimiento de la solución', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.tipoprocedimiento'),
        ),
        migrations.AlterField(
            model_name='tipoprocedimiento',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización'),
        ),
        migrations.AlterField(
            model_name='tipoprocedimiento',
            name='tipDescripcion',
            field=models.TextField(db_comment='Aquí se hace una descripción del tipo de procedimiento', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tipoprocedimiento',
            name='tipNombre',
            field=models.CharField(db_comment='nombre del tipo de procedimiento', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaHoraActualizacion',
            field=models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userFoto',
            field=models.ImageField(blank=True, db_comment='Foto del Usuario', null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userTipo',
            field=models.CharField(choices=[('Administrativo', 'Administrativo'), ('Instructor', 'Instructor')], db_comment='Tipo de usuario', max_length=15),
        ),
    ]
